### ISSUE TITLE
updateSize optional smooth transition

### ISSUE THREAD

**Issue by SisDK** [bokuweb/re-resizable#151]
Feature request: 
Can updateSize have an optional smooth transition? Just to make the updateSize look smooth.

**Comment by bokuweb** [comment]
@SisDK Thanks for your report.
`smooth transition` means animation??

**Comment by SisDK** [comment]
@bokuweb Yea, animation. Would be great to have that.

**Comment by plan8studios** [comment]
This can be accomplished with a little CSS targeting the div that gets resized... 

```.the-div-that-resizes { transition: width 0.2s; }```

**Comment by bokuweb** [comment]
@plan8studios Thanks :)
@SisDK  Would  you please try it??

**Comment by bokuweb** [comment]
Please re-open it if you need.
