### ISSUE TITLE
Node not found?!

### ISSUE THREAD

**Issue by arcifius** [bokuweb/re-resizable#155]
I'm using react-resizable-box 4.0.0
My browser is: Mozilla Firefox / Chrome

### Expected behavior
It should just remove it normally on ComponentWillUnmount

### Actual behavior
![image](https://user-images.githubusercontent.com/11210923/31291653-db08c5d0-aaa6-11e7-8e75-40a1eefc6bfd.png)
i'm having an issue on last line of this...

console outputs "NotFoundError: Node was not found"

**Comment by arcifius** [comment]
I don't know why u are using this base thing but
```
//parent.removeChild(base);
```
solved the issue...

**Comment by bokuweb** [comment]
@arcifius Thanks for your report. I add workaround for now and published as v4.0.2.
If it is not fixed, could you please provide reproduced project on webpackbin??

https://www.webpackbin.com/bins/-Kvnrpd3GSG6-z0tpgH_

**Comment by arcifius** [comment]
@bokuweb i'll provide a project soon... the base element was messing up my layout so i've added an extra css to it ``` display: none ``` but i was using another libraries too... Anyways i'll try to make a reproduced version as soon as possible, thanks for your attention on this issue.

**Comment by argnist** [comment]
I get an error only when use it in Storybook:

> Cannot read property 'parentNode' of undefined
> TypeError: Cannot read property 'parentNode' of undefined
>     at Resizable.get$$1 (http://localhost:9009/static/preview.bundle.js:93598:29)
>     at Resizable.componentWillUnmount (http://localhost:9009/static/preview.bundle.js:93315:27)

It points to return this.resizable.parentNode;
this.resizable is undefined in this position.

**Comment by bokuweb** [comment]
@arcifius Thanks!!

**Comment by bokuweb** [comment]
Could you please try v4.4.1 ?
