### ISSUE TITLE
Can't resize height if it's given in percents

### ISSUE THREAD

**Issue by mrfuxi** [bokuweb/re-resizable#158]
### Overview of the problem
I'm using re-resizable **version** 4.0.2   

https://www.webpackbin.com/bins/-KygHWlVVmSeZtaH2rc3

My **browser** is:   
   
Chrome 62.0 and Firefox 56

### Description

Can't resize height if it's given in `%`, width works fine with `%`.
OnResize event it firing correctly with events, but the actual shape does not change.

### Steps to Reproduce

* Set the size to something using int values.
* Validate it resizes in both directions
* Change width to `%`
* Validate it resizes in both directions
* Change width back to int (or not, it does not matter)
* Change height to `%`
* Can not resize height anymore

### Expected behavior

Can resize heigh if given in `%`, same as width

**Comment by bokuweb** [comment]
@mrfuxi Thanks for your report. Would you please set `height 100%` for parents.

https://www.webpackbin.com/bins/-KyhDI5DGsujawXfh3_b

- index.html
```
<style>
        html, body, #app {
          width: 100%;
          height: 100%;
        }
</style>
```

- Hello.js
```
    <div style={{ height: '100%' }}>
      <Resizable
        style={{ background: '#ddd', display: 'inline-block' }}
        defaultSize={{ width: '40%', height: '20px' }}
      >
        Working
      </Resizable>
      <Resizable
        style={{ background: '#F00', display: 'inline-block' }}
        defaultSize={{ width: '40%', height: '20%' }}
      >
        Borken
      </Resizable>
    </div>
```

**Comment by mrfuxi** [comment]
Thank you, that helps!

**Comment by secreter** [comment]
if the parent use `display:flex;` and child use`defaultSize={{ width: '40%'}}`,it doesn`t work
