### ISSUE TITLE
Element width id="__resizable0" breaks my layout

### ISSUE THREAD

**Issue by Sinozet** [bokuweb/re-resizable#162]
I'm using re-resizable 4.0.3
My browser is Chrome
What is "__resizable0" element in DOM tree? It totally breaks my layout. Can I remove or customize it?

**Comment by bokuweb** [comment]
@Sinozet Thanks for your report.
It is necessary to use % size.

Would you please provide reproduced project (please use this skeleton https://www.webpackbin.com/bins/-Kvnrpd3GSG6-z0tpgH_) ?

**Comment by Sinozet** [comment]
> "This bin doesn exist anymore, sorry"
In few words, I have a simple flex container with row direction and 2 children divs with "flex-grow: 1" attribute. I want 2nd to be resizable.

**Comment by bokuweb** [comment]
oops, sorry correct url is below.

https://www.webpackbin.com/bins/-Kvnrpd3GSG6-z0tpgH_

**Comment by Sinozet** [comment]
Something like that https://www.webpackbin.com/bins/-L-p4pHi28RprUNEkvV2

**Comment by bokuweb** [comment]
@Sinozet Thanks for your report :) Would you please try using v4.1.1?

**Comment by Sinozet** [comment]
Now everything works fine, thanx for such a quick fix )
