### ISSUE TITLE
Text select while resizing in IE11

### ISSUE THREAD

**Issue by Sinozet** [bokuweb/re-resizable#166]
I'm using re-resizable 4.1.1

Bug appears in IE11.
I can't provide reproduced project on webpackbin, cos webpackbin doesn't work in my IE11.

When I drag resize handle, the text around became seleted sometimes.
In my case, this bug appears with complext layout, when animation framerate slows down.

I solved that by adding "-ms-user-select: none; user-select: none;" to handle style;  
"user-select: none" just for safity.

**Comment by bokuweb** [comment]
@Sinozet I add user-select none to handler. would you please try using 4.1.2

**Comment by Sinozet** [comment]
It still doesn't work in IE11. I see new 'user-select' style in most browsers, but in IE11 there is no one attrs at al for some reasonl.
