### ISSUE TITLE
Resizable container jumps to height from previous state when resizing began.

### ISSUE THREAD

**Issue by Sinozet** [bokuweb/re-resizable#168]
I'm using re-resizable 4.1.2   
Chrome 62

There is a height changing handler in component. When height changed by setState somewhere, click to bottom handle. It jumps to height from previous state. I want to remove this shaking.

https://www.webpackbin.com/bins/-L0EL7WEi-xXHKFIZDvW

The problem seems to be in Resizable component state, where state.width isn't equal to props.size.width sometimes.

**Comment by bokuweb** [comment]
@Sinozet Thanks for your report and reproduced project. I'll do some investigation.

**Comment by Sinozet** [comment]
Here is rough temporary fix, maybe it will help you.
https://www.webpackbin.com/bins/-L0PJ2ScuXcx2359DQrM

**Comment by travisdahl** [comment]
Seeing the same behavior.

**Comment by bokuweb** [comment]
@Sinozet @travisdahl Fixed by v4.2.1.
