### ISSUE TITLE
impossible to set minWidth to 0

### ISSUE THREAD

**Issue by hbogs** [bokuweb/re-resizable#175]
### Overview of the problem

I'm using re-resizable **version** [4.2.1]   

### Description

Setting a minimumsize to 0 will result in the minimum size to be 10px, ref this line: https://github.com/bokuweb/re-resizable/blob/master/src/index.js#L411

Why is this limitation set?

### Expected behavior

That the element should be allowed to resize to 0px

### Actual behavior

Minimum size is 10px

**Comment by bokuweb** [comment]
@hbogs Thanks for your report :) I see. I'll fix it.

**Comment by hbogs** [comment]
Cool, thanks. I see you added PR Welcome label - if you want, I can try looking into this later today.

**Comment by bokuweb** [comment]
@hbogs Would you please create PR, if you get a chance :)
