### ISSUE TITLE
Resizing only width sets height to fixed px value

### ISSUE THREAD

**Issue by hbogs** [bokuweb/re-resizable#179]
Bug

### Overview of the problem
I'm using re-resizable 4.3.0
   
Could you please provide reproduced project on webpackbin with latest version rnd?
No, the webpackbin link is broken. https://www.webpackbin.com/bins/-Kvnrpd3GSG6-z0tpgH_ 

My **browser** is:   Chrome 63, Firefox 57
   
### Description
When resizing width, height is calculated and set to a fixed px value.  This is problematic if you want height to always be initial/auto, and still be able to resize width. Setting size/defaultSize does not affect this.

It is the same problem when resizing height, then a fixed px value is set on width.

### Steps to Reproduce
1. Add resizable element
2. Start resizing width
3. Observe height is also set to a fixed px value.

### Expected behavior
I would expect height to not be modified when only resizing width. Same goes for resizing only height, I would expect only height to be modified.

### Actual behavior
Height is modified and set to a fixed px value.

**Comment by bokuweb** [comment]
@hbogs Fixed by #180, could you please try v4.3.1 ?

**Comment by hbogs** [comment]
Works great, thanks for the quick fix!
