### ISSUE TITLE
Drag after mouse release

### ISSUE THREAD

**Issue by clynchnovetta** [bokuweb/re-resizable#185]
Bug

I'm using re-resizable@^4.2.1.
I am using FireFox.
Three/six of my coworkers have this problem. Doesn't seem to be a mac/windows problem or chrome/firefox problem.

I have noticed that sometimes when I go to drag a component wrapped in re-resizable the resizing does not stop. This seems to happen when you drag from the left to the right fast. You let go of the mouse and the component does not resize. It still thinks it is being dragged. I have two divs, one being the Resizable component and another just a plain div. It seems to start acting weird if the plain div has a lot of children.

**Comment by liuzhiyuan1993** [comment]
I got similar problems in electron.

**Comment by bokuweb** [comment]
@clynchnovetta Thanks for your report :) Hmmm, I can not reproduce it... But, I add tiny change to mouse event handler. Could you please try v4.4.4+ id you get a chance.
