### ISSUE TITLE
set size to 0 can't update component but set to 0px can do it

### ISSUE THREAD

**Issue by IronLu233** [bokuweb/re-resizable#218]
### Overview of the problem

I'm using re-resizable **4.4.6** 
   

My **browser** is:   
   Chrome
I am sure this issue is **not a duplicate**?
Yes
### Steps to Reproduce

1. Create a controlled Resizable component.
2. Set the size to 0 (the size is a property in a state) .
3. Component will not change it's size.
4. Set the size to 0px.
5. Component will update it's size.

**Demo**
https://codesandbox.io/s/kxyl8nr397

### Expected behavior
component can resize to 0 with giving 0 or 0px

### Actual behavior

component don't resize to 0
### if this actually is a bug ,Can I pull a request for it?

**Comment by bokuweb** [comment]
@IronLu233 Thanks for your report :) I'll do investigation.

**Comment by bokuweb** [comment]
@IronLu233 fixed. Could you please try v4.4.7 ?

**Comment by IronLu233** [comment]
It works well. Thank you very much!
