### ISSUE TITLE
RemoveChild bug when nested re-resizable

### ISSUE THREAD

**Issue by Jason121250148** [bokuweb/re-resizable#220]
version 4.4.7, browser: chrome v65
When I use re-resizable inside another re-resizble like this:
`<Resizable>
      <Resizable>
      </Resizable>
</Resizable>
`
it reports bug at componentWillUnmount
![image](https://user-images.githubusercontent.com/10795499/37943745-6b222a90-31ab-11e8-9df1-4859a9d2056d.png)
![image](https://user-images.githubusercontent.com/10795499/37943842-e414c0de-31ab-11e8-9c76-428c8e7088a3.png)

I think this is caused by nested component, when the parent Resizable unmounts, it remove its child's ___resizable_base__, so when the child remove his __resizable_base__, he can not find it!
The solution i suggest is that saving the "__resizable_base__ element" as an variable in component OR judge if "__resizable_base__" is his child when removing.

**Comment by bokuweb** [comment]
@Jason121250148 Thanks for your report. I'll do investigation.

**Comment by bokuweb** [comment]
@Jason121250148 Fixed, could you please try the latest version?
