### ISSUE TITLE
Div with __resizable_base__ remains after component is unmounted.

### ISSUE THREAD

**Issue by joetidee** [bokuweb/re-resizable#224]
I am extending `<Resizeable/>` using `styled-components` like this:

```
const ResizableSC = styled(Resizable)``;
export const StyledPane = ResizableSC.extend`
    box-sizing: border-box;
    display: inline-block;
    padding: ${remAuto(13)} 0;
`;
```

When `<StyledPane/>` is rendered, using Chrome dev tools, I can see an additional div that is place directly after `<StyledPane/>` in the DOM:

`<div class="__resizable_base__" style="width: 100%; height: 100%; position: relative; transform: scale(0, 0); left: -2.14748e+09px; flex: 0 1 0%;"></div>`

When `<StyledPane/>` is unmounted, this extra div remains in the DOM and I would assume that it shouldn't (?). It is throwing out the layout of the remaining page.

I'm using re-resizable v4.4.4

**Comment by bokuweb** [comment]
@joetidee Hi :) Thanks for your report. Could you please provide reproduced project? (https://codesandbox.io/s/xp9p7272m4)

**Comment by joetidee** [comment]
Thanks for the quick response. I upgraded to 4.4.8 and the div is now being removed on unmount.
