### ISSUE TITLE
How to style handle hover?

### ISSUE THREAD

**Issue by Marc22** [bokuweb/re-resizable#232]
Is there a way to style a particular handle when the cursor is hovering over it?

I don't see a way for the calling component to know when mouseEnter/mouseLeave events happen for a handle, so that the calling component can change the handle style.

Any suggestions?  thanks...

**Comment by Marc22** [comment]
never mind... I can accomplish what I need with handleClasses.  Thanks!

**Comment by kaleem-elahi** [comment]
@Marc22 Hi, How did you use `handleClasses ` ?

**Comment by Slapbox** [comment]
Presumably they work like this (from another library from the same author)

https://github.com/bokuweb/react-rnd#resizehandlestyles-handlestyles
