### ISSUE TITLE
THIS PACKAGE IS NO LONGER IN NPM

### ISSUE THREAD

**Issue by Narvey** [bokuweb/re-resizable#234]
`npm install re-resizeable`

Results in:

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/re-resizeable
    npm ERR! 404
    npm ERR! 404  're-resizeable' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

So here I am bugging you to publish it.

**Comment by Narvey** [comment]
actually I upgraded to the latest version of npm and [now it works, BUT WHY?](https://www.codetee.com/products/my-code-works-but-why-my-code-does-not-work-but-why) because `npm config get registry` still shows https://registry.npmjs.org/, and https://registry.npmjs.org/re-resizeable still returns a 404.

**Comment by bokuweb** [comment]
typo?
