### ISSUE TITLE
Any examples of usage with flexbox?

### ISSUE THREAD

**Issue by joetidee** [bokuweb/re-resizable#238]
I am trying to use this package with a `flexbox` container:
https://codesandbox.io/s/1qovv1vy4

Is there any way to get this woking so that each `Pane` can be resized ?

**Comment by bokuweb** [comment]
@Hi. would you please check this example ? http://bokuweb.github.io/re-resizable/?selectedKind=multiple&selectedStory=horizontal%20%28with%20flex%20layout%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by joetidee** [comment]
Fantastic - do you have the source code for it?
