### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your componentfrom the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by kirbudnik** [bokuweb/re-resizable#256]
I'm using re-resizable@4.4.8 and got this error when rendering.
I've two components - one is parent and another one contains `Resizable`.

Without `Resizable`, it works correctly, but if I added this, I always get this error.

**Comment by bokuweb** [comment]
@kirbudnik Thanks for your report. would you please provide reproduced project with codesandbox?
https://codesandbox.io/s/xp9p7272m4

**Comment by cpwinn** [comment]
I'm having the same problem with version 4.7.1 off npm. I can't replicate it on codesandbox. I was able to get around the issue by replacing my import with
`const Resizable = require('re-resizable').default;`
I don't know if that is a clue or not. Maybe its related to how I'm packaging with webpack.

**Comment by olegsmetanin** [comment]
> I'm having the same problem with version 4.7.1 off npm. I can't replicate it on codesandbox. I was able to get around the issue by replacing my import with
> `const Resizable = require('re-resizable').default;`
> I don't know if that is a clue or not. Maybe its related to how I'm packaging with webpack.

Does not work for me. "re-resizable": "4.9.0",  "webpack": "4.16.5",  "typescript": "3.0.3"

**Comment by bokuweb** [comment]
@kirbudnik @thomastanck @olegsmetanin I rewritten by typescript.
Please write following.

```
import { Resizable } from "re-resizable";
```

**Comment by Slapbox** [comment]
@bokuweb can we add this to the readme?
