### ISSUE TITLE
Custom handle not displaying

### ISSUE THREAD

**Issue by mraak** [bokuweb/re-resizable#354]
I took the code from[ this example](https://bokuweb.github.io/re-resizable/?selectedKind=handleComponent&selectedStory=bottom%20right&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and tried using it in a Code Sandbox. However the resize handle doesn't appear. 

https://codesandbox.io/s/w2plpoq2l

Is there an issue or am I missing something obvious?

**Comment by bokuweb** [comment]
@mraak Could you please check your function order.

https://codesandbox.io/s/ypvvl92yov
