### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [bokuweb/re-resizable#372]
I just saw the package is updated to `v4.9.1`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by MichaelDeBoey** [comment]
CC @bokuweb

**Comment by bokuweb** [comment]
@MichaelDeBoey Please see https://github.com/bokuweb/re-resizable#changelog for now.
