### ISSUE TITLE
CHANGELOG still missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [bokuweb/re-resizable#390]
I just saw the package is updated to `v4.10.0`, but I still can't find any CHANGELOG to check out the changes and can't find them in the README either.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

Duplicates #372

**Comment by bokuweb** [comment]
@MichaelDeBoey Sorry. I forgot. I update README for now.

The `scale` prop is added in v4.10.0

https://github.com/bokuweb/re-resizable#scale-number
