### ISSUE TITLE
CHANGELOG still missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [bokuweb/re-resizable#396]
I just saw the package is updated to `v4.11.0`, but I still can't find any CHANGELOG to check out the changes and can't find them in the README either.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

Duplicates #390

**Comment by bokuweb** [comment]
@MichaelDeBoey Sorry 😢 
I added `resizeRatio` props in v4.11.0

**Comment by MichaelDeBoey** [comment]
@bokuweb No prob 🙂
Maybe add an issue  template where it's stated to add something to the CHANGELOG?
