### ISSUE TITLE
Resizable child element has hidden popover

### ISSUE THREAD

**Issue by witoldmetel** [bokuweb/re-resizable#445]
### Overview of the problem

I'm using re-resizable **version** [4.11.0]

### Description

Element has tooltip which is hidden. I try a lot of CSS hacks for that but I don't find any solution. 

### Steps to Reproduce

https://codesandbox.io/s/fervent-blackburn-y37g2

### Expected behavior

Tooltip shouldn't be hidden

### Actual behavior

Tooltip is hidden
![Peek 2019-05-31 12-44](https://user-images.githubusercontent.com/31034370/58704845-ac9c0e00-83ad-11e9-89c1-39eeaf93cf36.gif)

**Comment by bokuweb** [comment]
@witoldmetel please remove `overflow:hidden` from `.container`

**Comment by witoldmetel** [comment]
This isn't a solution to the problem. I want to be able to hide the elements inside the container.

That's effect without `overflow: hidden`:
![test](https://user-images.githubusercontent.com/31034370/58932903-d1a1cf80-8765-11e9-9bdc-bb721b7691b4.png)
