### ISSUE TITLE
Types do not work with emotion-styled

### ISSUE THREAD

**Issue by aleccool213** [bokuweb/re-resizable#456]
### Overview of the problem

=I'm using re-resizable 5.0.1  

My **browser** is: Chrome/Brave
   
### Description

Seems like types are not working with emotion-styled components anymore with the new version.

### Steps to Reproduce

https://codesandbox.io/embed/infallible-cookies-fe59l

### Expected behavior

Compiles with Typescript.

### Actual behavior

Errors like:

```
This JSX tag's 'children' prop expects type 'never' which requires multiple children, but only a single child was provided.
```

occur.

**Comment by bokuweb** [comment]
@aleccool213 Thanks for your report. However I can not reproduce it.
You run into above error with codesandbox example??

**Comment by aleccool213** [comment]
Hmmm, just yesterday it wasn't working :( Ill close for now as it seems to have fixed itself :)
