### ISSUE TITLE
Fix deprecated componentWillRecieveProps lifecycle method usage

### ISSUE THREAD

**Issue by nerrad** [bokuweb/re-resizable#504]
### Overview of the problem

I'm using re-resizable **version** [5.0.1].  As implemented in the [WordPress Gutenberg Project](https://github.com/WordPress/gutenberg/blob/master/packages/components/package.json) in the `@wordpress/components` package.

My **browser** is:   Chrome
   
I am sure this issue is **not a duplicate**? Yes

### Description

The `componentWillReceiveProps` lifecycle method is deprecated in React and beginning in React 17 will [stop working](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops).  React in strict mode will show a warning for its usage.  re-resizable implements this lifecycle method here: 

https://github.com/bokuweb/re-resizable/blob/7ea154470567735149d5e3827cc9fb856f8e8f68/src/index.tsx#L463-L465

**Comment by bokuweb** [comment]
@nerrad Please try v6.0.0 :)

**Comment by nerrad** [comment]
Confirmed fixed.  Thanks for the quick turnaround - much appreciated :)
