### ISSUE TITLE
minHeight and minWidth when included the component does not resize

### ISSUE THREAD

**Issue by vodasaurabh** [bokuweb/re-resizable#521]
### Overview of the problem

My **browser** is:   
   
Google Cgrome

### Description

minHeight and minWidth when included the component does not resize

### Steps to Reproduce

1. Hit this URL "https://codesandbox.io/s/heuristic-galileo-g4bcy"
2. Copy paste following code
import React from "react";
import { render } from "react-dom";
import { Resizable } from "re-resizable";

const style = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  border: "solid 1px #ddd",
  background: "#f0f0f0",
  minHeight: "200px",
  minWidth: "200px"
};

const App = () => (
  <Resizable
    style={style}
    defaultSize={{
      width: 200,
      height: 200
    }}
    minHeight="100px"
    minWidth="100px"
  >
    001
  </Resizable>
);

render(<App />, document.getElementById("root"));

3. See the result

https://codesandbox.io/s/ll587k677z

### Expected behavior

Should be able to resize.

### Actual behavior
Not able to resize.

**Comment by walnutpedia** [comment]
same here. maxWidth also makes resize stop working.

**Comment by hhvys** [comment]
Try without px. or simply pass number as value of minHeight/minWidth

**Comment by walnutpedia** [comment]
> Try without px. or simply pass number as value of minHeight/minWidth

thanks! it works for me.

**Comment by vodasaurabh** [comment]
Works for me too. Thank you so much!

**Comment by bokuweb** [comment]
@hhvys thanks :)

**Comment by andys8** [comment]
@bokuweb It looks like `size` accepts `"100px"`, but `minWidth` doesn't. Wouldn't it make sense to have them accept the same values for consistency reasons?

https://www.npmjs.com/package/re-resizable#size--width-number--string-height-number--string-
https://www.npmjs.com/package/re-resizable#minheight-number--string
