### ISSUE TITLE
Support for vw, vh unit for maxWidth, maxHeight

### ISSUE THREAD

**Issue by hhvys** [bokuweb/re-resizable#525]
### Overview of the problem

I'm using re-resizable 6.0.0

My **browser** is:  Chrome
   
I am sure this issue is **not a duplicate**? Not sure

### Description
re-resizable currently supports defaultSize property related to the viewport, it will be helpful if maxWidth and maxHeight can also be assigned relative to viewport.e.g. maxHeight="90vw"

### Steps to Reproduce
Please refer the link below

https://codesandbox.io/s/admiring-violet-tqi45

### Expected behavior
component should not resize when the width of component is more than 90% of the viewport.

### Actual behavior
maxHeight ending with % is being handled currently. but when it ends with vw or vh it breaks

**Comment by hhvys** [comment]
I have got an overview of the code and it seems there isn't any handling for viewport unit(vw, vh) for maxHeight/maxWidth. Please let me know if it is not intentional or I am missing something.

Also, if not intentional, can I fix this?

**Comment by bokuweb** [comment]
@hhvys Tanks for your report. I know however I don't have enough time to fix it.
If you are ok please create PR :+1:

**Comment by hhvys** [comment]
Taking it
