### ISSUE TITLE
Question: Does this work with Touch Events?

### ISSUE THREAD

**Issue by AO19** [bokuweb/re-resizable#574]
I'm using re-resizable **version** [6.2.0]   

My **browser** is:   Firefox/ Chrome

### Description

In the Demo in your Storybook, I tried using the multiple resizable example with a Touch Device. It did not trigger.

Does this library only support mouse events?

### Expected behavior

Resize on Touch Events.

### Actual behavior

No resize possible.

**Comment by burtonator** [comment]
Works for me...
