### ISSUE TITLE
'as' prop is not optional in typings. 

### ISSUE THREAD

**Issue by alexdaube** [bokuweb/re-resizable#629]
### Overview of the problem

I'm using re-resizable **6.4.0 **  
 
### Description

The latest 6.4.0 release specifies the addition of the optional prop `as?: string | React.ComponentType<any>` to the component, which should default to div.

That said, looking at the interface inside **index.d.ts** for `ResizableProps`. The `as` prop appears mandatory.
![image](https://user-images.githubusercontent.com/8660478/83824830-820e2080-a6a5-11ea-8be2-b6f3f5acf54a.png)

### Steps to Reproduce
1. Use re-resizable within a typescript project 
2. Upgrade re-resizable to 6.4.0
3. Notice that typescript won't compile without adding the `as` prop to the component. 

### Expected behavior

The `as` prop should be optional.

### Actual behavior

The `as` prop is mandatory.

**Comment by bokuweb** [comment]
@alexdaube Thanks 6.5.1 published
