### ISSUE TITLE
TouchEvent error in Firefox, on version 6.5.2

### ISSUE THREAD

**Issue by palcikaman** [bokuweb/re-resizable#643]
Is it a bug/feature/question or do you need help?
Bug.

If it's a bug, is it a browser bug?
Firefox doesn't support TouchEvent.

### Overview of the problem

I'm using re-resizable **version** [6.5.2]   
   

My **browser** is:   
Firefox
   
I am sure this issue is **not a duplicate**?
Yes

### Description

In Firefox it throws the following error when trying to resize:
ReferenceError
TouchEvent is not defined
evaluate/Resizable.prototype.onMouseMove
https://1vwo2p4l64.csb.app/node_modules/re-resizable/lib/index.js:558:9

### Steps to Reproduce

1. Use the library in Firefox

https://codesandbox.io/s/ll587k677z

### Expected behavior

To be able to resize the component.

### Actual behavior

I can't resize the component

**Comment by bokuweb** [comment]
@palcikaman Sorry... Thanks for your report. It is fixed #644. Please use 6.5.4

**Comment by palcikaman** [comment]
That was some really fast response. Thanks for the fix!
