### ISSUE TITLE
unable to resize when setting a minWidth in pixels

### ISSUE THREAD

**Issue by natomato** [bokuweb/re-resizable#663]
### Overview of the problem

I'm using re-resizable **version** [6.5.4]   
   

My **browser** is:  Chrome, latest
   
I am sure this issue is **not a duplicate**? yes

### Description

Unable to reseize with minWidth in pixels.

### Steps to Reproduce

1. set a minWidth in pixels, and resizing stops, but I expect it to work with pixels as well as percents.
```
  <Resizable
    style={style}
    defaultSize={{
      width: '20%',
      height: 200
    }}
    minWidth={'150px'}
    enable={{right: true}}  
  >
```

https://codesandbox.io/s/sad-worker-w9y6t?file=/src/index.js:268-421

### Expected behavior

resizable container

### Actual behavior

width does not change

**Comment by daodaoker** [comment]
<Resizable
    style={style}
    defaultSize={{
      width: '20%',
      height: 200
    }}
    minWidth='150'
    enable={{right: true}}  
  >

like this，i have test it, it works.

**Comment by daodaoker** [comment]
> ### Overview of the problem
> I'm using re-resizable **version** [6.5.4]
> 
> My **browser** is: Chrome, latest
> 
> I am sure this issue is **not a duplicate**? yes
> 
> ### Description
> Unable to reseize with minWidth in pixels.
> 
> ### Steps to Reproduce
> 1. set a minWidth in pixels, and resizing stops, but I expect it to work with pixels as well as percents.
> 
> ```
>   <Resizable
>     style={style}
>     defaultSize={{
>       width: '20%',
>       height: 200
>     }}
>     minWidth={'150px'}
>     enable={{right: true}}  
>   >
> ```
> 
> https://codesandbox.io/s/sad-worker-w9y6t?file=/src/index.js:268-421
> 
> ### Expected behavior
> resizable container
> 
> ### Actual behavior
> width does not change

<Resizable
style={style}
defaultSize={{
width: '20%',
height: 200
}}
minWidth='150'
enable={{right: true}}

like this，i have test it, it works.

**Comment by bokuweb** [comment]
@natomato @daodaoker Sorry, it is fixed by https://github.com/bokuweb/re-resizable/pull/676 please try latest version.

**Comment by bokuweb** [comment]
@daodaoker Thanks :)
