### ISSUE TITLE
Div with __resizable_base__ SHOULD remain after component is unmounted

### ISSUE THREAD

**Issue by manuFL** [bokuweb/re-resizable#667]
Hi, I'm having issues related to the behaviour mentioned in issue #224 

I think that __resizable_base__ item should be removed upon unmounting **only** if there are not other siblings re-resizable components.

In my scenario, for example, I'm using percentage sizes with several re-resizable components; all of them are children of the same parent div. If I destroy one of them, all the resizes events are broken also for the others, due to __resizable_base__ removal. If I then create a new component, it puts back the __resizable_base__ and all is back working as it should.

My suggested fix is to check whether there are other mounted components before removing this important item.

Thank you in advance for your support, keep up the great job!

**Comment by manuFL** [comment]
Hi, there is any ETA for the fix? Thank you in advance!

**Comment by bokuweb** [comment]
@manuFL I changed to create base element when needed. Please try tv6.5.0

**Comment by manuFL** [comment]
Seems to work great now, thank you very much!
