### ISSUE TITLE
Resizing from left, top and topLeft results in opposite edge moving during drag

### ISSUE THREAD

**Issue by swillis12** [bokuweb/re-resizable#684]
Edit: I believe this is common/desired behavior, if this can be done through the current API perhaps we can close the issue and document it here.

### Overview of the problem
Resizing only works as expected when dragging from the right/bottom since this does not require updating position and only width/height. When resizing from left or top the "left" and "top" position values need to be updated so that the edge that the user is dragging is moved and not the opposite edge. If this is not feasible then there should be a way to override this behavior while the edge is being dragged (~~and give an event to listen to current mouse position delta from starting point in order to update the size -- without this users will have to add their own mouse event listeners~~ Edit: I think this can be done with onResize event).

I'm using re-resizable 6.5.0
   

Reproducible on the documentation codesandbox: https://codesandbox.io/s/xp9p7272m4 (preview video has background color changed for better visibility)

My **browser** is:   Chrome Version 85.0.4183.121 Mac OS 10.15.7

   
I am sure this issue is not a duplicate after searching the issues for "left" and "top" resize. I found no mention of this behavior in the documentation.

### Description

Resizing from left, top and topLeft results in opposite edge moving during drag. 
![Oct-05-2020 10-39-29](https://user-images.githubusercontent.com/35236833/95113292-142b4180-06f7-11eb-85fe-596028696679.gif)

### Steps to Reproduce

1. Resize from left, top or topLeft.

### Expected behavior

1. The edge that the user is dragging should move OR the consumer should be able to update the style as the box is being dragged (to change left and top styles).

### Actual behavior

Opposite edge from what is being dragged moves

**Comment by kayesn786** [comment]
@swillis12 , even am facing the same issue

**Comment by nopol10** [comment]
Encountered this issue as well, then found out about the author's other repository [https://github.com/bokuweb/react-rnd](https://github.com/bokuweb/react-rnd) which seems to do the job

**Comment by martisj** [comment]
Any luck with this repo? `react-rnd` is a few times larger than this repo.

**Comment by SimeonRolev** [comment]
@bokuweb Is it on purpose that `react-rnd` supports this, and this one doesn't? Is it on the TODO list?

**Comment by bokuweb** [comment]
@SimeonRolev

> Is it on purpose that react-rnd supports this

Yes.

**Comment by RewriteH** [comment]
why it's closed? lol.

**Comment by AJLoveChina** [comment]
Hi bros, I am late but it may help somebody  CC @bokuweb 

https://codesandbox.io/s/gifted-ully-csh6s4

![re-resizable-top-left-resize-unexpected-behaviour-2](https://github.com/bokuweb/re-resizable/assets/11222746/99462a2f-a4c3-470d-a31d-56b2147394ba)

**Comment by Mayonnaisu** [comment]
> why it's closed? lol.

I guess the owner just doesn't want to fix it, considering his/her answer to the question above.

@AJLoveChina Thanks!
