### ISSUE TITLE
 HTML validation: Element “div” not allowed as child of element “span”

### ISSUE THREAD

**Issue by binhpv** [bokuweb/re-resizable#705]
### Overview of the problem

I'm using re-resizable **version** [6.8.0]   
   

This is a problem of HTML Syntax and can be reproduce on any browser
   
I am sure this issue is **not a duplicate**

### Steps to Reproduce
This can be reproduce at official storybook: https://bokuweb.github.io/re-resizable/

Inspecting HTML will show that the handler divs are wrapped inside a span.

### Expected behavior

The div should be wrapped inside a div to be valid HTML

### Actual behavior

divs are wrapped inside a span

**Comment by binhpv** [comment]
Hi @bokuweb , this issue is blocking our application from verification of accessibility. Could you have a look at my PR if that's ok? Thanks a bunch.

**Comment by bokuweb** [comment]
@binhpv 6.9.0 is published
