### ISSUE TITLE
Resizable content is not displayed when using component in as

### ISSUE THREAD

**Issue by anomerova** [bokuweb/re-resizable#723]
### Overview of the problem

I'm using re-resizable version 6.9.0
   

My browser is: Chrome

I am sure this issue is not a duplicate.

### Description

I am using Resizible to changing the width of the headers in a table. If I specify the string 'th' in 'as' props, then the content of the header is displayed normally. If I use a functional component, the title is not displayed correctly.

### Steps to Reproduce

The component is wrapped in ForwardRef because we cannot use ref in a functional component.
Replacing the component with a HOC does not affect the error.

https://codesandbox.io/s/re-resizable-header-on-table-irzdg

### Expected behavior

The content of the headers is displayed, the column is resize

### Actual behavior

The content of the headers is not displayed, resize does not work

**Comment by anomerova** [comment]
The transfer of the component as a variable helped.
However, in the form (props) => <TableCell {...props} /> resize still does not work.

**Comment by WORLDI** [comment]
hello, do you resolve this problem?
