### ISSUE TITLE
When stretched diagonally on the left, the block zoomed in or out incorrectly

### ISSUE THREAD

**Issue by Fuyuwei-Fxx** [bokuweb/re-resizable#740]
When stretched diagonally on the left, the block zoomed in or out incorrectly. I hope the point on the left can follow the drag

https://user-images.githubusercontent.com/39211654/120444608-5ad25800-c3ba-11eb-8564-396837fe2b67.mp4

**Comment by stijn-gravity** [comment]
From what I can understand this is on purpose as it would require updating the position. You could overwrite the position yourself using the `onResize`, however this is a lot of work.

I hope there is a way to turn off specific edges/corners. This would make the UX a little better.

@bokuweb, is this possible? I was unable to find this in the API reference.

**Comment by bokuweb** [comment]
Please use https://github.com/bokuweb/react-rnd

**Comment by stijn-gravity** [comment]
@bokuweb awesome, thanks for pointing me this way.
