### ISSUE TITLE
Changelog for version 6.9.7 and 6.9.8

### ISSUE THREAD

**Issue by Tirzono** [bokuweb/re-resizable#771]
On npm there's a version 6.9.7 and 6.9.8. There are no changelog entries for these versions and it looks like the commits are also not here on GitHub. Would it be possible to add a changelog with the changes and push the commits that are part of 6.9.7 and 6.9.8?

**Comment by bokuweb** [comment]
Sorry I added. 6.9.7 is abandoned version
