### ISSUE TITLE
onResize fired before snapping to grid

### ISSUE THREAD

**Issue by dingzhanjun** [bokuweb/re-resizable#783]
### Overview of the problem

I'm using re-resizable **version** [6.9.6]   
   

My **browser** is:   Safari and Chrome
   
I am sure this issue is **not a duplicate**?

### Steps to Reproduce

1. First Step, add a Resizable component to app and set grid to [10, 10], add onResize callback
2. Second Step, run app and try to resize it

### Expected behavior
onResize gets fired when resize happens 

### Actual behavior
onResize gets fired whenever mouse move during the process of resizing(with snapping)

**Comment by bokuweb** [comment]
https://github.com/bokuweb/react-rnd/issues/901
