### ISSUE TITLE
6.9.10 is a empty package

### ISSUE THREAD

**Issue by DreamGhostStar** [bokuweb/re-resizable#791]
### Overview of the problem

I'm using re-resizable **version** [6.9.10]   
   
I am sure this issue is **not a duplicate**? yes

### Description

![image](https://github.com/bokuweb/re-resizable/assets/48384290/9bc94ea6-f1eb-459a-9b73-5005a33c8784)

Download version 6.9.10 found it to be an empty NPM package

**Comment by ClaudioMuselli90** [comment]
The issue on my opinion is related to a wrong labeling of the release here on github... 6.6.10 instead of 6.9.10 please correct

**Comment by bokuweb** [comment]
Oops, sorry. 6.9.11 published could you please try this?

**Comment by DreamGhostStar** [comment]
> 

It runs very well, good!

**Comment by DreamGhostStar** [comment]
> Oops, sorry. 6.9.11 published could you please try this?

It runs very well, good!
