### ISSUE TITLE
re-resizable@6.9.10 is not working

### ISSUE THREAD

**Issue by wkexinpd** [bokuweb/re-resizable#792]
![image](https://github.com/bokuweb/re-resizable/assets/49779820/467dad9b-b745-4579-9820-e3d4ebc0bf96)
The lib directory is empty!

**Comment by ClaudioMuselli90** [comment]
The issue on my opinion is related to a wrong labeling of the release here on github... 6.6.10 instead of 6.9.10 please correct

**Comment by keweeks** [comment]
For the moment, I've had to set `"re-resizable": "6.9.9",` in my package.json

**Comment by bokuweb** [comment]
Oops, sorry. 6.9.11 published could you please try this?
