### ISSUE TITLE
When using a scale and html element boundary the scale is not applied to the bounds.

### ISSUE THREAD

**Issue by cor1** [bokuweb/re-resizable#820]
Bug

### Overview of the problem

When using a scale and html element boundary the scale is not applied to the bounds.

I'm using re-resizable **version** 6.9.16 
   

My **browser** is:   Chrome
   
I am sure this issue is **not a duplicate**? Yes

### Steps to Reproduce

1. Apply a transform scale on the element that is the boundary
2. resize and the sizing boundary is off.

### Expected behavior

Even with a scale on the parent, the boundary should stay the same and follow what the user sees.

### Actual behavior

The resize stops (hits the boundary) in an unexpected place.

**Comment by bokuweb** [comment]
@cor1 Thanks for your work. Could you please provide a codesandbox project to reproduce this issue?

**Comment by cor1** [comment]
@bokuweb Apologize for the delay, here is a codesandbox showing boundaries being off when scaling is applied
https://codesandbox.io/p/sandbox/hardcore-meitner-t4nhsw?file=%2Fsrc%2Findex.js
to see the issue, resize the window so the red area scales down.

**Comment by bokuweb** [comment]
@cor1 Sorry for late. Thanks for your work :) I'll check.

**Comment by cor1** [comment]
@bokuweb no worries, thanks so much!

**Comment by cor1** [comment]
hey @bokuweb any update?
