### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by dgtllion** [bokuweb/re-resizable#839]
is there a plan to make re-resizeable work with React 19?
When i try to upgrade to React 19 with pnpm i get warning that your package is not supporting React 19.

```
├─┬ re-resizable 6.10.1
  ├── ✕ unmet peer react@"^16.13.1 || ^17.0.0 || ^18.0.0": found 19.0.0-rc-66855b96-20241106
  └── ✕ unmet peer react-dom@"^16.13.1 || ^17.0.0 || ^18.0.0": found 19.0.0-rc-66855b96-20241106

```

**Comment by dgtllion** [comment]
@bokuweb any update on this? React 19 is out now and its already month later.

**Comment by bokuweb** [comment]
@dgtllion sorry I'll check it later

**Comment by bokuweb** [comment]
published

**Comment by dgtllion** [comment]
@bokuweb may be i miss something... but when i try to install latest version 16.0.2 react doesnt sees the package... when i move back to 16.0.1 then it does.

What i do:
- pnpm add re-resizable

```
dependencies:
+ re-resizable 6.10.2
```

When i look website then it gives me an error couldn't find module.
