### ISSUE TITLE
6.10.2 MISSING the lib content

### ISSUE THREAD

**Issue by arvinxx** [bokuweb/re-resizable#842]
@bokuweb 

just check it here: https://www.npmjs.com/package/re-resizable?activeTab=code

<img width="993" alt="image" src="https://github.com/user-attachments/assets/ff808f97-3337-4e64-953d-67b1e0315a2d">

it casue our deployment failed: https://github.com/lobehub/lobe-chat/issues/4937

Please fix it ASAP. Thanks.

**Comment by lihqi** [comment]
The same [issue](https://github.com/open-mmlab/labelbee/actions/runs/12230301574/job/34111459899?pr=618)

**Comment by Traveller23** [comment]
same here.

**Comment by iugin** [comment]
same here

**Comment by bokuweb** [comment]
sorry 6.10.3 published
